### ISSUE TITLE
modCalibrator() and modSimulator()

### ISSUE THREAD

**Issue by rubyleigh** [ClimateAnalytics/foreSIGHT#1]
In the modelTag documentation, there is a list of available rainfall models to use. Only  "P-ann-wgen" and "P-seas-wgen" work, the harmonic models do not. "P-har-wgen" works but it is unclear which harmonic model is being used.

**Comment by dmcinern** [comment]
Hi Ruby,
Thanks for raising this issue (a long time ago now!).
Currently, only one harmonic model is implemented in foreSIGHT for parameter variations (with a single annual period). 
I have removed the other list of model names from the documentation for modCalibrator() and modSimulator().
Cheers,
David
